const express = require("express");
const route = express.Router();
const upload = require("../../middlewares/upload");
const controller = require("../../controllers/adminController/product.controller");
route.get("/", controller.getAllProducts);
route.get("/:id", controller.getProductById);
route.post("/create", upload.array("images", 10), controller.createProduct);
route.put("/edit/:id", upload.array("images", 10), controller.updateProduct);
route.delete("/delete/:id", controller.deleteProduct);
route.patch("/toggle/:id", controller.toggleProductActive);
module.exports = route;
